### ISSUE TITLE
"Cannot read property '0' of undefined" in no-sanitizer-with-danger.js

### ISSUE THREAD

**Issue by chris-schembri-webjet** [Jam3/eslint-config-jam3#6]
I'm getting the "Cannot read property '0' of undefined" error on a TypeScript file, originating from the no-sanitizer-with-danger.js file from the return section after line 80.

I've managed to suppress the error by adding `Array.isArray(node.value.expression.properties)` to each of the if statements like so:

`
        if (isDangerous(node.name.name) && Array.isArray(node.value.expression.properties) && node.value.expression.properties[0].value.type !== 'CallExpression') {
          messageIndex = 0;
        } else if (
          isDangerous(node.name.name) && Array.isArray(node.value.expression.properties) && 
          node.value.expression.properties[0].value.type === 'CallExpression' &&
          node.value.expression.properties[0].value.callee.type === 'Identifier' &&
          config.wrapperName.indexOf(node.value.expression.properties[0].value.callee.name) === -1
        ) {
          messageIndex = 1;
        } else if (
          isDangerous(node.name.name) && Array.isArray(node.value.expression.properties) && 
          node.value.expression.properties[0].value.type === 'CallExpression' &&
          node.value.expression.properties[0].value.callee.type !== 'Identifier'
        ) {
          messageIndex = 2;
        }
`

But the fix isn't ideal and I thought asking one of you could get a better solution. I have a feeling it may be ESLint / TypeScript / Prettier / DOMPurify related as I'm still trying to get ESLint errors to appear after installing DOMPurify/Jam3 to my project.

**Comment by riffaud** [comment]
Having the same issue here
